
const getMunicipios = () => {

    return municipios = [
        "Bacalar",
        "Benito Juárez",
        "Cozumel",
        "Felipe Carrillo Puerto",
        "Isla Mujeres",
        "José María Morelos",
        "Lázaro Cárdenas",
        "Othón P. Blanco",
        "Puerto Morelos",
        "Solidaridad",
        "Tulum",
    ];

}



const getColonias = ( municipio ) => {

    switch ( municipio ) {
        case 'Othón P. Blanco':   
            return [
                "10 de Septiembre",
                "16 de Septiembre",
                "20 de Noviembre",
                "5 de Abril",
                "8 de Octubre",
                "Adolfo López Mateos",
                "Aeropuerto",
                "Allende",
                "Álvaro Obregón Viejo",
                "Álvaro Obregón",
                "Andara",
                "Andrés Quintana Roo",
                "Aserradero",
                "Avancemos Juntos",
                "Bahía",
                "Barrio Bravo",
                "Benito Juárez",
                "Bicentenario",
                "Bosques del Lago",
                "Bugambilias",
                "Cacao",
                "California",
                "Campestre",
                "Caobas",
                "Caribe",
                "Carlos A Madrazo",
                "Cascada I",
                "Cascadas II",
                "Cedro",
                "Cedros",
                "Centenario",
                "Centro Calderitas",
                "CERESO Chetumal",
                "Chetumal (Internacional de Chetumal)",
                "Chetumal Centro",
                "Cocoyol",
                "Comité Proterritorio",
                "Constituyentes",
                "David G Gutiérrez Ruiz",
                "Del Bosque",
                "Del Mar I y II (Infonavit)",
                "Dos Aguadas",
                "El Cedral",
                "El Encanto",
                "El Sol",
                "Emiliano Zapata",
                "Espíritu Santo",
                "Estatuto Jurídico (FOVISSSTE 5a Etapa)",
                "Esteban Baca Calderón",
                "Félix Gonzalez Canto",
                "Flamingos",
                "Forjadores de Quintana Roo",
                "Fovissste  IV Etapa",
                "Fovissste (I Etapa)",
                "Fovissste (II Etapa)",
                "Fovissste VI Etapa (Tampico)",
                "Framboyanes",
                "Francisco J Mújica INFONAVIT",
                "Francisco Villa",
                "Gonzalo Guerrero",
                "Guadalupe Victoria",
                "Hacienda Chetumal",
                "Hidalgo",
                "Huaypix",
                "Industrial",
                "Infonavit 17 de Octubre",
                "Infonavit Aarón Merino Fernández",
                "Infonavit Álvaro Obregón",
                "Infonavit Emancipación",
                "Infonavit Enrique Ramírez y Ramírez",
                "Infonavit Fidel Velázquez",
                "Infonavit Hermanos Flores Magón",
                "Infonavit Santa María",
                "Infonavit Villas Chetumal",
                "Isabel Tenorio",
                "Italia",
                "Jardines de Payo Obispo",
                "Jardines",
                "Javier Rojo Gómez",
                "Jesús González Ortega",
                "José Narciso Rovirosa",
                "Josefa Ortiz de Domínguez",
                "Juan Sarabia",
                "Kilómetro 5",
                "La Conquista",
                "La Esperanza",
                "La Libertad",
                "La Unión",
                "Laguna Guerrero",
                "Lagunitas",
                "Las Américas",
                "Las Arboledas",
                "Las Brisas",
                "Lázaro Cárdenas Segundo",
                "Lázaro Cárdenas",
                "Leona Vicario",
                "Ley Federal de Agua",
                "Limonar",
                "Lomas del Caribe",
                "Los Almendros",
                "Los Arcos",
                "Los Monos",
                "Luis Echeverría Álvarez",
                "Magisterial",
                "Mahahual",
                "Martínez Ross",
                "Maya Real",
                "Milenio",
                "Militar",
                "Miraflores II",
                "Miraflores",
                "Morocoy",
                "Nachi-cocom",
                "Naval",
                "Nueva Generación",
                "Nuevo Bécar",
                "Nuevo Caanán",
                "Nuevo Progreso",
                "Oxtankah",
                "Pacto Obrero Campesino",
                "Palmar",
                "Payo Obispo",
                "Pedro Joaquín Coldwell",
                "Playa Uvero",
                "Plutarco Elías Calles",
                "Primera Legislatura",
                "Proterritorio",
                "Pucte",
                "Rafael E Melgar FOVISSSTE",
                "Ramonal",
                "Raudales",
                "Reforma",
                "Residencial Arboledas",
                "Residencial Bosque Real",
                "Residencial Caribe",
                "Residencial Chetumal",
                "Residencial Constituyentes",
                "Residencial del Sol",
                "Residencial la Herradura",
                "Residencial Marsella",
                "Residencial Mediterráneo",
                "Revolución",
                "Sabidos",
                "Sacxán",
                "SAHOP",
                "San Francisco Botes",
                "San José de la Montaña",
                "San Pedro Peralta",
                "Santa Isabel",
                "Sergio Butrón Casas",
                "Sian Kaan II",
                "Sian Kaan",
                "Solidaridad",
                "Subteniente López",
                "Sutage INFONAVIT",
                "Tamalcab",
                "Taxistas",
                "Territorio Federal de Quintana Roo",
                "Tomás Garrido",
                "Tres Garantías",
                "Tumben Cuxtal",
                "Ucum",
                "Unidad Antorchista",
                "Venustiano Carranza (Casitas)",
                "Veracruz",
                "Villas Kinichna",
                "Xcalak",
                "Xul-ha",
                "Yucatán",
                "Zona de Granjas",
            ];
            

        case 'Felipe Carrillo Puerto':
            return [
                "Andrés Quintana Roo",
                "Betania",
                "Cecilio Chi",
                "Chan Santa Cruz",
                "Chancah Derrepente",
                "Chancah Veracruz",
                "Chumpón",
                "Chun On",
                "Chun-Yah",
                "Chunhuás",
                "Chunhuhub",
                "Constituyentes",
                "Dzoyola",
                "Dzulá",
                "Emiliano Zapata",
                "Felipe Carrillo Puerto Centro",
                "Filomeno Mata",
                "Francisco I. Madero",
                "Francisco May",
                "Hobompich",
                "Ignacio Manuel Altamirano",
                "Javier Rojo Gómez",
                "Jesús Martínez Ross",
                "José María Pino Suárez",
                "Juan Bautista Vega",
                "Kampokolché",
                "Kancabchén",
                "Kopchen",
                "Laguna Kaná",
                "Lázaro Cárdenas",
                "Leona Vicario",
                "María Villanueva Madrid",
                "Mixtequilla",
                "Naranjal Poniente",
                "Noh-Bec",
                "Noh-Cah",
                "Nueva Loría",
                "Nuevo Israel",
                "Petcacab",
                "Plan de Ayala",
                "Plan de Ayutla",
                "Plan de Guadalupe",
                "Plan de La Noria",
                "Polyuc",
                "Presidente Juárez",
                "Rafael E Melgar",
                "Ramonal",
                "Reforma Agraria",
                "San Andrés",
                "San Felipe Berriozábal",
                "San Francisco Aké",
                "San José Segundo",
                "San Ramón",
                "Santa Amalia",
                "Santa María Poniente",
                "Santa Rosa Segundo",
                "Señor",
                "Tabi",
                "Tepich",
                "Tihosuco",
                "Tixcacal Guardia",
                "Trapich",
                "Tuzik",
                "Uh May",
                "X-Hazil Sur",
                "X-Konha",
                "X-Pichil",
                "X-Yatil",
                "Yalchén",
                "Yaxley",
                "Yoactún",
                "Yodzonot Chico",
            ]

        case 'Lázaro Cárdenas':  
            return [
                "1 de Mayo",
                "1 de Septiembre",
                "10 de Mayo",
                "10 de Octubre",
                "11 de Julio",
                "13 de Septiembre",
                "15 de Enero",
                "16 de Mayo",
                "17 de Octubre",
                "1er. Sector FIDELAC",
                "2 de Febrero",
                "20 de Agosto",
                "2do. Sector FIDELAC",
                "3 de Mayo",
                "5 de Mayo 3er Sector",
                "5 de Mayo 4to Sector",
                "5 de Mayo Poniente",
                "5 de Mayo",
                "600 Casas",
                "Acalpican de Morelos",
                "Aeropuerto",
                "Agrícola Gordiano Guzmán",
                "Agua Azul",
                "Almacenes",
                "Álvaro Obregón",
                "Amalia Solórzano",
                "Ampliación 1 de Mayo",
                "Ampliación 2 de Febrero",
                "Ampliación 5 de Mayo",
                "Ampliación Aeropuerto",
                "Ampliación Aníbal Ponce",
                "Ampliación Aserradero",
                "Ampliación Benito Juárez",
                "Ampliación Emiliano Zapata",
                "Ampliación Ignacio Allende",
                "Ampliación Independencia",
                "Ampliación Insurgentes",
                "Ampliación Jarene",
                "Ampliación Javier Mina",
                "Ampliación La Estrella",
                "Ampliación La Orillita",
                "Ampliación Lucio Cabañas",
                "Ampliación Lucrecia Toriz",
                "Ampliación Palmira",
                "Ampliación Paraíso",
                "Ampliación Roma",
                "Ampliación Técnica 91",
                "Ampliación Villa Hermosa",
                "Aníbal Ponce",
                "Antorchista",
                "Aquiles Serdán",
                "Arboledas",
                "Argentina",
                "Arroyo del Barco",
                "Aserradero",
                "Atlixtaca",
                "Azteca",
                "Benigno Trejo",
                "Benito Juárez",
                "Boca Seca",
                "Borcelano",
                "Bordonal",
                "Borge Martín",
                "Brisamar",
                "Buenavista",
                "Buenos Aires",
                "Caleta de Campos",
                "Camino Real",
                "Campamento CFE",
                "Campamento CNA",
                "Campamento Minero",
                "Campamento Obrero \"Francisco J. Mujica\"",
                "Capa",
                "Celerino Cano",
                "Centro",
                "Cerrito de Álvarez",
                "Chiquila",
                "Chucutitán",
                "Chuquiapan",
                "Chuta",
                "Comunal Morelos",
                "Condesa",
                "Constituyentes del Setenta y Cuatro",
                "COPALAC",
                "CROM Estibadores",
                "Crucero el Habillal",
                "Cuauhtémoc",
                "Del Carmen",
                "Delirios",
                "Ejidal",
                "Ejido Zona II",
                "Ejido",
                "El Canalote",
                "El Carrizalillo",
                "El Cedral",
                "El Cerrito del Capire (El Habillal)",
                "El Cerrito",
                "El Colomo (San Miguel)",
                "El Coral",
                "El Destierro",
                "El Girasol",
                "El Guayabo Sur (El Jazmín)",
                "El Guayabo Sur",
                "El Habillal",
                "El Ideal",
                "El Manguito",
                "El Mirador",
                "El Naranjal",
                "El Palmar",
                "El Palomar",
                "El Pescador",
                "El Pocito",
                "El Puertecito",
                "El Reyno",
                "El Río de Nexpa",
                "El Sembrador",
                "El Tahuazal",
                "El Tintal",
                "El Triangulito",
                "El Tular",
                "El Veladero",
                "Emiliano Zapata",
                "Ernesto Zedillo",
                "Esperanza",
                "Expo",
                "Ferrocarrileros",
                "Flamingos II",
                "Flamingos",
                "Flor de Abril I",
                "Flor de Abril II",
                "Flor de Abril III",
                "Francisco Sarabia",
                "Guacamayas Comercial",
                "Héroe de Nacozari",
                "Ignacio Allende",
                "Ignacio Zaragoza",
                "Independencia",
                "INFONAVIT Nuevo Horizonte",
                "INFONAVIT Solidaridad Nacional",
                "Insurgentes",
                "Irekani",
                "Isla de Holbox",
                "Isla del Cayacal",
                "Jardines",
                "Jarene",
                "Javier Mina",
                "Jose Green",
                "José Ma. Morelos",
                "José Vasconcelos",
                "Juan F. Noyola",
                "Kantunilkin Centro",
                "La Antorcha",
                "La Báscula",
                "La Ceiba",
                "La Colorada",
                "La Coquillera",
                "La Corregidora",
                "La Escondida",
                "La Estrella",
                "La Florida",
                "La Huerta",
                "La Joya",
                "La Limonera",
                "La Loma",
                "La Mancera",
                "La Manzanilla",
                "La Milpillera",
                "La Mira",
                "La Orilla",
                "La Orillita",
                "La Parotilla",
                "La Paz",
                "La Primavera",
                "La Principal",
                "La Salada (La Saladita)",
                "La Soledad",
                "La Soyamiche",
                "La Tabiquera",
                "La Villita I",
                "La Villita II",
                "La Villita",
                "Las Calabacillas",
                "Las Calabazas",
                "Las Camelinas",
                "Las Canoas",
                "Las Colinas",
                "Las Flores Celestes",
                "Las Gardenias",
                "Las Higueras",
                "Las Juntas",
                "Las Lomas",
                "Las Minitas",
                "Las Palmas",
                "Las Parotas",
                "Las Peñas",
                "Las Teresitas",
                "Las Torres",
                "Las Truchas",
                "Lázaro Cárdenas III",
                "Lázaro Cárdenas",
                "Leandro Valle",
                "Leonardo Rodríguez Alcaine",
                "Libertad",
                "Linda Vista",
                "Lindavista",
                "Loma Bonita",
                "Lomas de Bellavista",
                "Lomas de las Cenizas",
                "Lomas del Río (Unidad 5.12)",
                "Lomas del Valle",
                "Los Almendros",
                "Los Amates",
                "Los Bocotes",
                "Los Canales",
                "Los Cedros",
                "Los Coyotes",
                "Los Girasoles",
                "Los Hornos",
                "Los Jiotes",
                "Los Lavaderos",
                "Los Llanitos",
                "Los Llanos del Bejuco (El Bejuco)",
                "Los Manguitos",
                "Los Parajes",
                "Los Pinitos",
                "Los Poetas",
                "Los Taxistas",
                "Los Transportistas",
                "Lotes y Servicios",
                "Lucio Cabañas",
                "Lucrecia Toriz",
                "Luis Aguilar Ceja",
                "Luis Donaldo Colosio",
                "Luz del Mar (Barra de Pichi)",
                "Magisterial",
                "Mancha de Uje",
                "Margarita Morán",
                "Maribel",
                "Marina Universidad",
                "Melchor Ocampo",
                "Mexcalhuacán",
                "México",
                "Miguel de Cervantes Saavedra",
                "Miguel Hidalgo",
                "Miramar",
                "Monte Bello",
                "Movimiento Urbano Popular",
                "Napoleón Gómez Sada",
                "Naval",
                "Nexpa (Neixpa)",
                "Niños Héroes",
                "Nuevo Quintana Roo",
                "Nuevo Xcan",
                "Obrera",
                "Palmira",
                "Paraíso",
                "Pie de La Casa",
                "Playa Azul",
                "Playa Rangel",
                "Plutarco Elías Calles",
                "Polanco",
                "Popoyuta",
                "Popular INDECO",
                "Praderas Verdes",
                "Presidencial",
                "Progreso Nacional",
                "Puente de la Vía",
                "Puente del Toro",
                "Puente La Vía",
                "Puerto Nuevo",
                "Puerto Pacífico",
                "Puerto Real",
                "Puesta del Sol",
                "Purepecha",
                "Reforma",
                "Renacimiento",
                "Renovación Sindical",
                "Respuesta Social",
                "Revolución",
                "Ricardo Flores Magón",
                "Rinconada del Balsas",
                "Rinconcito",
                "Río Balsas",
                "Riveras Del Rio",
                "Samuel Ruiz",
                "San Ángel",
                "San Antonio",
                "San Blas",
                "San Felipe de Jesús",
                "San Francisco",
                "San José de la Laguna",
                "San Juan Bautista",
                "San Juan Bosco",
                "San Juan de Dios",
                "San Lorenzo",
                "San Martiniano",
                "San Miguel Arcángel",
                "San Pedro",
                "San Rafael del Reino (Arroyo de la Tierra)",
                "San Rafael",
                "San Román",
                "Saneco",
                "Santa Cecilia",
                "Santa Margarita",
                "SARH",
                "Solera de Agua",
                "Solferino",
                "Técnica 91",
                "Teolán",
                "Terencio Tah",
                "Tres Marias",
                "Tres Reyes",
                "Tulipanes",
                "Unidad 3.11",
                "Unidad 3.12",
                "Unidad 3.2",
                "Unidad 5.13",
                "Unidad 5.9",
                "Unidad Deportiva",
                "Unidad y Progreso",
                "Universidad Vasco de Quiroga (El Manglito)",
                "Valladolid Nuevo",
                "Valle Bonito",
                "Valle Del Tecnológico",
                "Valle Escondido",
                "Vicente Guerrero",
                "Victor Manuel Tinoco Rubí",
                "Villa del Tecnológico",
                "Villa Hermosa",
                "Villa Jardín",
                "Viña del Mar",
                "Vista Hermosa Aeropuerto",
                "Vista Hermosa",
                "Vista Industrial",
                "Xaman - Kah",
                "Zona Industrial",
            ]
        
        case 'Isla Mujeres':   
            return [
                "23 de Noviembre",
                "Ampliación la Gloria",
                "Bahía",
                "Caribeña",
                "Caridad del Cobre",
                "Del Bosque",
                "Del Sureste",
                "El Cañotal",
                "El Nazareno",
                "Electricistas",
                "Isla Blanca",
                "Isla Mujeres Centro",
                "Isla Mujeres",
                "Islote de Carbonera",
                "Islote El Yunque",
                "La Gloria",
                "La Guadalupana",
                "Lagunamar",
                "Las Américas",
                "Lolbe",
                "Mar Caribe",
                "Metereológico",
                "Miraflores",
                "Monte Olivo",
                "Nueva Tierra",
                "Prolongación Aeropuerto",
                "Puerto de Abrigo",
                "Punta Gaviota",
                "Salina Chica",
                "Salina Grande",
                "Santa Rosa",
                "Supermanzana 1",
                "Vista Alegre",
            ]

        case 'Benito Juárez':  
            return [
                "3 Hermanos",
                "8 de Agosto",
                "ABC",
                "Abel Placencia",
                "Acacias",
                "Aceitunitas (Sube y Baja)",
                "Actipan",
                "Agua Blanca",
                "Álamos I",
                "Álamos",
                "Albert",
                "Alfonso Souque",
                "Alfredo V Bonfil",
                "Almacén Bonfil",
                "Américas Unidas",
                "Ampliación Nápoles",
                "Ampliación Progreso",
                "Aquiles Souque",
                "Arbolada",
                "Arboledas",
                "Arcos Paraíso",
                "Arenal de Alvarez",
                "Arenal de Gómez",
                "Arenal del Centro",
                "Atenor Salas",
                "Atlalco",
                "Azoquitipa",
                "Azul Bonampak",
                "Bachoco",
                "Bahía Dorada",
                "Bahía Real",
                "Batevito (Colonia Irrigación)",
                "Benito Escalante",
                "Benito Juárez",
                "Bosques San Miguel",
                "Calle 19",
                "Campestre",
                "Campo Aída Puertas",
                "Campo Arreola",
                "Campo Arvizu",
                "Campo Ballesteros",
                "Campo Carlos Laugher",
                "Campo Castelo",
                "Campo Córdova",
                "Campo de Alfonso Hermosillo",
                "Campo de Anselmo Cubedo",
                "Campo de Antonio Fuerte",
                "Campo de Jesús Gutiérrez",
                "Campo de Jesús Saldívar",
                "Campo de la Viuda",
                "Campo de Pedro Dueñas",
                "Campo de Rubén Dorame",
                "Campo del Gringo",
                "Campo Don Rufino",
                "Campo Fernando Gutiérrez",
                "Campo Gil",
                "Campo Gildardo Vega",
                "Campo Gutiérrez",
                "Campo L",
                "Campo Liborio Rodríguez",
                "Campo Miranda",
                "Campo Parada (Costa Rica)",
                "Campo Reyna",
                "Campo Rivera",
                "Cancún (Internacional de Cancún)",
                "Cancún Centro",
                "Carlos Flores",
                "Casas del Mar",
                "Catania Residencial",
                "Central de Abasto",
                "Central de Abastos",
                "Chamuyil",
                "Chávez",
                "Chema Pérez",
                "Chila",
                "Chinotagueca la Loma",
                "Ciudad de los Deportes",
                "Coachumo Común",
                "Colegios",
                "Corea",
                "Costa del Mar",
                "Costa Rica (El Quirino)",
                "Costa Rica (Mayojusali)",
                "Crédito Constructor",
                "Cuatro Caminos",
                "Cuevas Chicas (Las Cuevas Chicas)",
                "Cuna Maya (Supermanzana 203)",
                "Del Carmen",
                "Del Lago",
                "Del Maestro",
                "Del Tiesto",
                "Del Valle Centro",
                "Del Valle Norte",
                "Del Valle Sur",
                "Doctores",
                "Donceles",
                "Ejido 15 de Mayo",
                "Ejido Alfredo V. Bonfil",
                "Ejido Primero de Mayo",
                "El Chaleco (Miguel Hidalgo)",
                "El Durazno",
                "El Estero Chico",
                "El Milagro",
                "El Tobarito",
                "El Tomatal",
                "Ermita",
                "Esmeralda",
                "Esquer",
                "Extremadura Insurgentes",
                "Fernando Gándara",
                "Fernando Navarro",
                "Fito",
                "Florencia de Benito Juárez",
                "Fraccionamiento Galaxia Altamar",
                "Framboyanes",
                "Francisco Villa",
                "Galaxia del Sol",
                "Galaxia las Torres",
                "Generación 2000",
                "General Pedro María Anaya",
                "Gran Santa Fe 2",
                "Gran Santa Fe",
                "Granja Bachoco",
                "Guerrero",
                "Hacienda de Cabañas",
                "Hacienda Del Rey",
                "Hacienda Real del Caribe",
                "Hidalgo",
                "Hueycuatitla",
                "Huizache",
                "Idalia Mejía",
                "In House",
                "Independencia",
                "Industrial",
                "Insurgentes Mixcoac",
                "Insurgentes San Borja",
                "Ixchel",
                "Ixtacahuayo",
                "Iztaccihuatl",
                "Jardines Cancún",
                "Jardines de Banampak",
                "Jardines del Sur",
                "Jecopaco",
                "Joaquín Preciado",
                "Josefa Ortiz de Domínguez",
                "Joselito",
                "Juan Souque",
                "Juárez",
                "La Amistad",
                "La Aviación",
                "La Azteca",
                "La Fresno Veinticinco",
                "La Guadalupana",
                "La Herradura",
                "La Joya (Supermanzana 254)",
                "La Laguna",
                "La Libertad",
                "La Lima",
                "La Morena",
                "La Reforma",
                "La Revancha",
                "Lagos del Sol",
                "Lagos",
                "Las Cruces",
                "Las Lajas",
                "Las Tablas",
                "Las Torres",
                "Las Tunas",
                "Letrán Valle",
                "Ley Echeverría Z U",
                "Llano de La Puerta",
                "Llano Grande",
                "Llano Real (El Dorado)",
                "Loma Bonita",
                "Lombardo Toledano",
                "Lora",
                "Los Campos",
                "Los Cedros",
                "Los Charcos",
                "Los Cipreses",
                "Los García",
                "Los Héroes",
                "Los Mirasoles",
                "Los Naranjos",
                "Los Órganos",
                "Los Primeros de Costa Rica",
                "Los Santos",
                "Los Sauces",
                "Los Tucanes (Supermanzana 242)",
                "Maderos Residencial",
                "Malbaso",
                "Malibú",
                "Mallorca",
                "Marco Antonio Gutiérrez",
                "Marco Mejía",
                "Marina Turquesa",
                "Merced Gómez",
                "Mesa de Arellanos",
                "Mesa de Núñez",
                "Mesa de Rayos",
                "México",
                "Miguel Alemán",
                "Miguel Hidalgo (El Moño)",
                "Mirador",
                "Miravalle",
                "Mixcoac",
                "Moderna",
                "Monte Real",
                "Nápoles",
                "Narvarte Oriente",
                "Narvarte Poniente",
                "Nativitas",
                "Niños Héroes",
                "Nochebuena",
                "Nuevo Amanecer",
                "Nuevo Milenio",
                "Nuevo Pedregal",
                "Otlamalácatl",
                "Palma Real",
                "Paltzoquitempa",
                "Paraíso Cancún",
                "Paraíso Maya",
                "Paraíso Villas",
                "Paraíso",
                "Paredón Colorado (Paredón Viejo)",
                "Paredoncito",
                "Paseo de Las Palmas",
                "Paseo Kusamil",
                "Paseo Nikté",
                "Paseo San Ángel",
                "Paseos Chac Mool",
                "Paseos del Mar",
                "Paseos del Sol (Supermanzana 205)",
                "Paseos Kabah",
                "Peñuñuri",
                "Periodista",
                "Petén",
                "Piedad Narvarte",
                "Portales Norte",
                "Portales Oriente",
                "Portales Sur",
                "Porto Alegre",
                "Postal",
                "Potrerillos",
                "Prado Norte (Supermanzana 256)",
                "Predio de la Familia Siqueiros",
                "Primo Verdad (San Miguel)",
                "Privada Altus",
                "Privadas Sacbe",
                "Privanza Stellaris",
                "Puerta Del Sol",
                "Punta Ikal",
                "Punta Sam",
                "Quetzales (Supermanzana 523)",
                "Quinta las Joyas",
                "Quintas Kavanayen",
                "Ramiro Almada",
                "Rancho Sánchez",
                "Raúl Gutiérrez",
                "Real Las Quintas (Supermanzana 202)",
                "Real Valencia",
                "Residencial Alejandría",
                "Residencial Caracol",
                "Residencial Cumbres",
                "Residencial Cuyagua",
                "Residencial Emperadores",
                "Residencial La Cascada",
                "Residencial San Antonio",
                "Residencial Sol del Mayab",
                "Residencial Turquesa",
                "Residencial Vista Alegre",
                "Rinconada Santa María",
                "Rinconadas del Mar",
                "Rosarito",
                "Sac-Be",
                "Salazar",
                "San Alfredo",
                "San Jerónimo de Juárez Centro",
                "San José Bonampack",
                "San José Insurgentes",
                "San José",
                "San Juan",
                "San Lucas Tepetitlán",
                "San Martín Caballero",
                "San Pedro de los Pinos",
                "San Salvador (Laguna Seca)",
                "San Salvador Barneche",
                "San Simón Ticumac",
                "Santa Anna (Supermanzana 301)",
                "Santa Cecilia",
                "Santa Cruz Atoyac",
                "Santa Fe (Supermanzana 524)",
                "Santa Fe Plus",
                "Santa Fe",
                "Santa María (Costa Rica)",
                "Santa María Nonoalco",
                "Solidaridad",
                "Supermanzana 1 Centro",
                "Supermanzana 10",
                "Supermanzana 100",
                "Supermanzana 101",
                "Supermanzana 102",
                "Supermanzana 103",
                "Supermanzana 104",
                "Supermanzana 105",
                "Supermanzana 106",
                "Supermanzana 107",
                "Supermanzana 11",
                "Supermanzana 117",
                "Supermanzana 12",
                "Supermanzana 13",
                "Supermanzana 14",
                "Supermanzana 15",
                "Supermanzana 15a",
                "Supermanzana 16",
                "Supermanzana 17",
                "Supermanzana 18",
                "Supermanzana 19",
                "Supermanzana 2 Centro",
                "Supermanzana 20 Centro",
                "Supermanzana 200",
                "Supermanzana 206",
                "Supermanzana 208",
                "Supermanzana 209",
                "Supermanzana 21",
                "Supermanzana 210",
                "Supermanzana 211",
                "Supermanzana 212",
                "Supermanzana 213",
                "Supermanzana 214",
                "Supermanzana 215",
                "Supermanzana 216",
                "Supermanzana 217",
                "Supermanzana 218",
                "Supermanzana 219",
                "Supermanzana 22 Centro",
                "Supermanzana 220",
                "Supermanzana 221",
                "Supermanzana 222",
                "Supermanzana 223",
                "Supermanzana 225",
                "Supermanzana 226",
                "Supermanzana 227",
                "Supermanzana 228",
                "Supermanzana 229",
                "Supermanzana 23 Centro",
                "Supermanzana 230",
                "Supermanzana 231",
                "Supermanzana 232",
                "Supermanzana 233",
                "Supermanzana 234",
                "Supermanzana 235",
                "Supermanzana 236",
                "Supermanzana 237",
                "Supermanzana 238",
                "Supermanzana 239",
                "Supermanzana 24",
                "Supermanzana 240",
                "Supermanzana 241",
                "Supermanzana 243",
                "Supermanzana 244",
                "Supermanzana 245",
                "Supermanzana 25",
                "Supermanzana 253",
                "Supermanzana 26",
                "Supermanzana 260",
                "Supermanzana 27",
                "Supermanzana 28",
                "Supermanzana 29",
                "Supermanzana 295",
                "Supermanzana 296",
                "Supermanzana 297",
                "Supermanzana 299",
                "Supermanzana 2a Centro",
                "Supermanzana 3 Centro",
                "Supermanzana 30",
                "Supermanzana 31",
                "Supermanzana 312",
                "Supermanzana 313",
                "Supermanzana 318",
                "Supermanzana 319",
                "Supermanzana 32",
                "Supermanzana 320",
                "Supermanzana 322",
                "Supermanzana 323",
                "Supermanzana 326",
                "Supermanzana 327",
                "Supermanzana 33",
                "Supermanzana 34",
                "Supermanzana 35",
                "Supermanzana 36",
                "Supermanzana 37",
                "Supermanzana 38",
                "Supermanzana 39",
                "Supermanzana 4 A",
                "Supermanzana 4 Centro",
                "Supermanzana 40",
                "Supermanzana 41",
                "Supermanzana 42",
                "Supermanzana 43",
                "Supermanzana 44",
                "Supermanzana 45",
                "Supermanzana 46",
                "Supermanzana 47",
                "Supermanzana 48",
                "Supermanzana 49",
                "Supermanzana 5 Centro",
                "Supermanzana 50",
                "Supermanzana 500",
                "Supermanzana 501",
                "Supermanzana 502",
                "Supermanzana 503",
                "Supermanzana 504",
                "Supermanzana 505",
                "Supermanzana 506",
                "Supermanzana 507",
                "Supermanzana 508",
                "Supermanzana 509",
                "Supermanzana 51",
                "Supermanzana 510",
                "Supermanzana 511",
                "Supermanzana 512",
                "Supermanzana 514",
                "Supermanzana 515",
                "Supermanzana 516",
                "Supermanzana 517",
                "Supermanzana 518",
                "Supermanzana 519",
                "Supermanzana 52",
                "Supermanzana 520",
                "Supermanzana 522",
                "Supermanzana 525",
                "Supermanzana 526",
                "Supermanzana 527",
                "Supermanzana 528",
                "Supermanzana 529",
                "Supermanzana 53",
                "Supermanzana 530",
                "Supermanzana 531",
                "Supermanzana 534",
                "Supermanzana 54",
                "Supermanzana 55",
                "Supermanzana 550",
                "Supermanzana 57",
                "Supermanzana 58",
                "Supermanzana 59",
                "Supermanzana 60",
                "Supermanzana 61",
                "Supermanzana 62",
                "Supermanzana 63",
                "Supermanzana 64",
                "Supermanzana 65",
                "Supermanzana 66",
                "Supermanzana 67",
                "Supermanzana 68",
                "Supermanzana 69",
                "Supermanzana 6a",
                "Supermanzana 6b",
                "Supermanzana 6c",
                "Supermanzana 6d",
                "Supermanzana 6e",
                "Supermanzana 6f",
                "Supermanzana 7",
                "Supermanzana 70",
                "Supermanzana 71",
                "Supermanzana 72",
                "Supermanzana 73",
                "Supermanzana 74",
                "Supermanzana 75",
                "Supermanzana 76",
                "Supermanzana 77",
                "Supermanzana 78",
                "Supermanzana 8",
                "Supermanzana 84",
                "Supermanzana 85",
                "Supermanzana 86",
                "Supermanzana 89",
                "Supermanzana 9",
                "Supermanzana 90",
                "Supermanzana 91",
                "Supermanzana 92",
                "Supermanzana 93",
                "Supermanzana 94",
                "Supermanzana 95",
                "Supermanzana 96",
                "Supermanzana 97",
                "Supermanzana 98",
                "Supermanzana 99",
                "Tecolotes",
                "Tenantitla",
                "Tierra Maya",
                "Tierra Nuestra Cancún",
                "Tierra y Libertad",
                "Tlacoquemécatl",
                "Tlatlapango Grande",
                "Tolico de Zapata",
                "Tonilco",
                "Universidad Anáhuac de Cancún",
                "Urbi Villas del rey",
                "Vargas",
                "Vértiz Narvarte",
                "Vicente Suárez",
                "Villa de Cortes",
                "Villa Juárez",
                "Villamarino",
                "Villas de Alba",
                "Villas del Arte",
                "Villas del Mar \"Plus\"",
                "Villas del Mar",
                "Villas del Sol II (Supermanzana 207)",
                "Villas del Sol",
                "Villas Otoch Paraíso",
                "Villas Otoch",
                "Villas Quintana Roo",
                "Villas Tropicales",
                "Vista Hermosa",
                "Vista Real",
                "Vitalá",
                "Xoco",
                "Yupiltitla",
                "Zacahuitzco",
                "Zona Hotelera",
            ]
        
        case 'Puerto Morelos':  
            return [
                "Aldea Civitas",
                "Joaquín Zetina Gasca",
                "La Nueva Esperanza",
                "Leona Vicario",
                "Puerto Morelos",
                "Residencial Alborada",
                "Residencial Civitas",
                "Residencial Regatta",
                "Selva Escondida",
                "Villas La Playa",
                "Villas Morelos I",
            ]
        
        case 'Cozumel':
            return [
                "10 de Abril",
                "Adolfo L. Mateos",
                "Altamar",
                "Andrés Q. Roo",
                "C T M",
                "CALICA",
                "Caribe",
                "Chen-tuk",
                "Colonos Cuzamil",
                "Cozumel (Internacional de Cozumel)",
                "Cozumel Centro",
                "Cozumel Turístico",
                "Cuzamil",
                "El Encanto",
                "Emiliano Zapata",
                "Félix González Canto",
                "Flamboyanes",
                "Flamingos I",
                "Flamingos II",
                "Flores Magón 1 y 2",
                "Flores Magón 3",
                "FOVISSSTE",
                "Huerto Familiar",
                "Independencia",
                "Ix-chel",
                "Juan Bautista de La Vega",
                "Las Golondrinas",
                "Magisterio",
                "Maravilla",
                "Militar",
                "Miraflores",
                "Naval",
                "Nueva Generación",
                "Repobladores de 1848",
                "San Gervasio",
                "San Miguel 1",
                "San Miguel 2",
                "San Miguel 3",
                "Taxistas",
                "Zona Hotelera Norte",
                "Zona Hotelera Sur",
                "Zona Industrial",
            ]

        case 'Solidaridad':  
            return [
                "28 de Julio",
                "Aviación",
                "Balamtun",
                "Bali",
                "Barceló Maya",
                "Bellavista",
                "Bosque de Cristo Rey",
                "Bosque Real",
                "Brisas",
                "Calica",
                "Campestre",
                "Cataluña II",
                "Cataluña",
                "Corales",
                "Cruz de Servicios",
                "Dunas",
                "Ejidal",
                "El Bambú",
                "El Cantil",
                "El Cielo",
                "El Pedregal",
                "El Petén",
                "El Tigrillo",
                "Encuentro",
                "Forjadores",
                "Fundadores",
                "Galaxia del Carmen I",
                "Galaxia del Carmen II",
                "Gonzalo Guerrero",
                "Grand Sirenis",
                "In House",
                "INFONAVIT Colosio",
                "INFONAVIT Gaviotas",
                "Jardines de Ciudad Mayakoba",
                "La Guadalupana",
                "La Joya Xamanha",
                "La Joya",
                "La Toscana",
                "Las Flores",
                "Las Palmas",
                "Lolkaatun",
                "Loltun",
                "Los Arrecifes",
                "Los Olivos",
                "Luis Donaldo Colosio",
                "Marsella",
                "Miramar",
                "Misión del Carmen",
                "Misión Las Flores",
                "Misión Villamar I",
                "Misión Villamar II",
                "Mundo Habitat",
                "Natura Playa del Carmen",
                "Nicte-ha",
                "Nueva Generación",
                "Nuevo Centro Urbano",
                "Paa Mul",
                "Palmanova",
                "Palmas II",
                "Paraíso del Carmen",
                "Parque Residencial",
                "Paseos Xcacel",
                "Pescadores Plus",
                "Playa Azul",
                "Playa Car Fase I",
                "Playa Car Fase II",
                "Playa del Carmen Centro",
                "Playa del Carmen",
                "Playa del Secreto",
                "Playa del Sol",
                "Playa Magna",
                "Porto Alto",
                "Privada Riviera",
                "Privanza del Mar",
                "Puerto Aventuras",
                "Puerto Maya",
                "Punta Estrella",
                "Quintas del Carmen",
                "Real Amalfi",
                "Real Bilbao",
                "Real Ibiza",
                "Real Lucerna",
                "Residencial Bambú",
                "Residencial Caribe",
                "Residencial La Escondida",
                "Residencial Playa Paraíso",
                "Residencial Real del Sol",
                "Sacpacal",
                "Santa Fe del Carmen",
                "Selvamar",
                "Solidaridad",
                "Tohoku",
                "Tumben Chilam",
                "Vela Mar",
                "Villas del Carmen Plus",
                "Villas del Carmen",
                "Villas del Sol \"Plus\"",
                "Villas las Perlas",
                "Villas Maya",
                "Villas Riviera",
                "Xamanha",
                "Xcaret",
                "Xpu Ha",
                "Zazil Ha",
                "Zona Industrial",
            ]
        
        case 'Tulum':   
            return [
                "Akumal",
                "Aldea Zama",
                "Bahías de Punta Solimán",
                "Boca Paila",
                "Chanchén Palmar",
                "Chanchen Primero",
                "Ciudad Chemuyil",
                "Cobá",
                "Ejidal",
                "Francisco Uh May",
                "Guerra de Castas",
                "Hondzonot",
                "Javier Rojo Gómez (Punta Allen)",
                "La Veleta",
                "Las Palmas",
                "Lúum Zama",
                "Macario Gómez",
                "Manuel Antonio Ay",
                "Maya Pax",
                "San Juan",
                "Tankah Cuatro",
                "Tulum Centro",
                "Tumben Kaa",
                "Villas Huracanes",
                "Villas Tulum",
                "Xul Kaa",
                "Ya Ax Tulum",
                "Yaxché",
            ]

        case 'José María Morelos':   
            return [
            "Adolfo de la Huerta",
            "Adolfo López Mateos",
            "Benito Juárez",
            "Bulukax",
            "Cafetalito",
            "Candelaria",
            "Dolores",
            "Dziuche",
            "El Martirio",
            "El Naranjal",
            "El Triunfo",
            "Gavilanes",
            "Guadalupana",
            "Guadalupe",
            "Huay Max",
            "Insurgentes",
            "Javier Rojo Gómez",
            "José María Morelos",
            "Kancabchén",
            "Kantemó",
            "Kilómetro 50",
            "La Esperanza",
            "La Presumida",
            "Lázaro Cárdenas",
            "Mariano Matamoros",
            "Mayab",
            "México",
            "Miraflores",
            "Nueva Reforma",
            "Nuevo Cunduacán",
            "Nuevo San Marcos",
            "Othón P. Blanco",
            "Piedras Negras",
            "Plan de la Noria Poniente",
            "Pocito",
            "Pozo Pirata",
            "Primavera",
            "Puerto Arturo",
            "Sabán",
            "Sabana San Francisco",
            "Sacalaca",
            "Saczuquil",
            "San Antonio Tuk",
            "San Carlos",
            "San Diego",
            "San Felipe Oriente",
            "San Felipe Primero",
            "San Felipe Segundo",
            "San Isidro Poniente",
            "San Juan Oriente",
            "San Juan",
            "Santa Gertrudis",
            "Santa Lucia",
            "Tabasco",
            "Venustiano Carranza",
            "Vicente Guerrero",
            "X-Cabil",
            "X-Querol",
            "Zafarrancho",
            ]

        case 'Bacalar':   
            return [
                "5 de Mayo",
                "Áak Abal",
                "Aarón Merino [Colonia]",
                "Aarón Merino",
                "Agua Real",
                "Ahisamac",
                "Alfonso Álvarez Sánchez",
                "Altos de Sevilla",
                "Anastacio Valdez Huchin",
                "Andrés Quintana Roo",
                "Ángelo Cortez",
                "Año Nuevo",
                "Arturo Martínez Colorado",
                "Astro Rey",
                "Bacalar Centro",
                "Bacalar Uno",
                "Bárbara Guerrero Pérez",
                "Benito Juárez",
                "Blanca Flor",
                "Buena Esperanza",
                "Buenavista",
                "Caan Lumil",
                "Caanán",
                "Cámara",
                "Cayuco Maya",
                "CECUSE",
                "Centro de Conservación e Investigación de la Vida",
                "Chacchoben",
                "Chula Vista",
                "Cinco Hermanos",
                "Colosio",
                "Corredor Frutícola",
                "Cruz del Sur",
                "Cuatro Banderas",
                "Cuatro Hermanos",
                "Cuatro Potrillos",
                "David Gustavo Gutiérrez Ruiz",
                "De Guadalupe",
                "Dieciocho de Marzo",
                "Diego Rojas",
                "División del Sur",
                "Ecotucán",
                "Eduardo Puchiga",
                "El Bajío",
                "El Buen Pastor",
                "El Cafetal",
                "El Calvario",
                "El Cedral",
                "El Cedralito",
                "El Cerro de la Campana",
                "El Coco",
                "El Diamante",
                "El Edén",
                "El Encanto Segundo",
                "El Encanto",
                "El Esfuerzo",
                "El Gallito",
                "El Higuero",
                "El Kiwi",
                "El Mamey",
                "El Milagro",
                "El Naranjal",
                "El Paraíso",
                "El Pedregal",
                "El Progreso",
                "El Ramonal",
                "El Remolino",
                "El Roble",
                "El Rubí",
                "El Sinaí",
                "El Sufrido",
                "El Suspiro",
                "El Trébol",
                "El Zapote",
                "Elsa Micaela Barquet",
                "Emiliano Pantín Góngora",
                "Ernesto Chejín",
                "Francisco Hurtado Ibarra",
                "Francisco J. Mújica",
                "Francisco Villa",
                "Frontera de los Julios",
                "Gabino Vázquez",
                "Gabriel García",
                "Gonzalo Guerrero",
                "Guadalupe Victoria",
                "Gustavo Antonio",
                "Gustavo Díaz Ordaz",
                "Huatusco",
                "Isidro Fabela",
                "Iturbide",
                "Iván Díaz",
                "Javier Palacios",
                "Javier Sandoval",
                "Jesús Martínez Ross",
                "Jorge Alonzo Canto",
                "Jorge Cano",
                "José Méndez",
                "Juan Herrera",
                "Kuchumatán",
                "La Bendición de Dios",
                "La Buena Fe",
                "La Candelaria",
                "La Carmelita",
                "La Casona",
                "La Ceiba",
                "La Central",
                "La Chata",
                "La Cochinera",
                "La Coruña",
                "La Esmeralda",
                "La Esperanza",
                "La Estancia",
                "La Herradura",
                "La Loma",
                "La Nueva Esperanza",
                "La Pantera",
                "La Pasadita",
                "La Piedra",
                "La Primavera",
                "La Prosperidad (El Aserradero)",
                "La Raya",
                "La Retranca",
                "La Zarza",
                "Las Brisas",
                "Las Dos Eses",
                "Las Heliconias",
                "Las Ilusiones",
                "Las Isabelas",
                "Las Maravillas",
                "Las Orquídeas",
                "Las Palmas",
                "Las Tres Emes",
                "Las Velas",
                "Laureles",
                "Lázaro Cárdenas del Río Tercero",
                "Lázaro Cárdenas",
                "Leyda Alpuche",
                "Limones",
                "Los Alacranes",
                "Los Ángeles",
                "Los Cardenales",
                "Los Cascabeles",
                "Los Cinco Hermanos",
                "Los Compadres",
                "Los Cuates",
                "Los Divorciados",
                "Los Humildes",
                "Los Laureles",
                "Los Siete Hermanos",
                "Los Socios",
                "Luis Donaldo Colosio",
                "Magisterial",
                "Manatí",
                "Manuel Ávila Camacho",
                "Margarita Maza de Juárez",
                "Mario Villanueva",
                "Marlboro",
                "Maya Balam",
                "Melchor Ocampo",
                "Miguel Alemán",
                "Miguel Hidalgo y Costilla",
                "Mil Millas al Sur",
                "Monte Olivo",
                "Narciso Alpuche Rivero",
                "Noh-Bec",
                "Nuevo Hoctún",
                "Nuevo Jerusalén",
                "Nuevo Tabasco",
                "Otilio Montaño",
                "Paraíso Escondido",
                "Paraíso Segundo",
                "Payo Obispo",
                "Pedro Antonio Santos",
                "Pehaltum",
                "Petén Tunich",
                "PROFEPA [Caseta de Vigilancia]",
                "Puerta del Cielo",
                "Punta Pulticub",
                "Rafael Witzil Hau",
                "Rancho Cascabel",
                "Rancho Encantado",
                "Rancho Grande",
                "Rancho Juanita",
                "Rancho Mayob",
                "Rancho Ramonal",
                "Rancho Sur",
                "Rancho Tranquila",
                "Reforma",
                "Reyna",
                "Río Escondido",
                "Río Verde",
                "Rosa de Saarón",
                "Sabanitas Dos",
                "Salamanca",
                "Salinas de Gortari",
                "San Antonio",
                "San Bernardo",
                "San Cosme",
                "San Felipe Bacalar",
                "San Felipe",
                "San Fernando",
                "San Gabriel",
                "San Isidro la Laguna",
                "San José (La Silvia)",
                "San José los Lirios",
                "San José",
                "San Juan",
                "San Judas Tadeo",
                "San Manuel",
                "San Martín",
                "San Pedro",
                "San Rafael",
                "San Ramón",
                "San Román",
                "San Víctor",
                "Santa Cruz Chico",
                "Santa Cruz",
                "Santa Julia",
                "Santa Rita",
                "Santa Rosa",
                "Santiago Palacios Carrillo",
                "Serapio Flota Mass",
                "Serviliano Cohuó Medina",
                "Silvia Cerecero Loyola",
                "Sistema de Bombeo",
                "Sócrates León Pérez",
                "Sor Juana Inés de La Cruz",
                "Tierra Negra",
                "Tito Raúl García Aguilar",
                "Tito",
                "Ubre Blanca",
                "Valentín Gómez Farías",
                "Vallehermoso",
                "Villas del Sagrario",
                "Xtomoc Uno",
                "Xtomoc",
                "Yumpetén",
                "Zak-Chakán",
                "Zamora",
                "Zapata",
            ];

        default:
            return [];
    }


}


module.exports = {
    getMunicipios,
    getColonias
}